version: '3.8'
services:
  nest-learn-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn-nest
    networks:
      - nest-network
networks:
  nest-network:
volumes:
  nest-db:
