name: Publish Image

on:
  push:
    branches:
      - main
      - test-github-action
  workflow_dispatch:

jobs:
  dockerize:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: docker-practice/actions-setup-docker@master
        timeout-minutes: 30
      - run: ls -a
      - name: Docker build
        run: docker build -t sagarbera/nest-learn:1.0 ./
      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io
      - name: Dockerhub push
        run: docker push sagarbera/nest-learn:1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
