name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install -g yarn
      - run: yarn
      - run: yarn build
      - uses: nick-fields/retry@v2
        with:
          max_attempts: 3
          timeout_seconds: 600
          retry_on: error
          retry_wait_seconds: 300
          command: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
